Add support for getting balance at a specific date
sdementen/piecash pull request #131
Opened 2019-12-27 14:23 UTC by rvijayc

I am creating a pull request that adds support to get account balance at a specific date. With this, we can - for example - get income (or expense) for a given year by subtracting the account balance at the start of the year from the account balance at the end of the year.

Please let me know if you have any questions.

2020-12-18 05:29 UTC, sdementen commented
Hello @rvijayc , could you add a corresponding test for the feature?

2020-12-29 07:31 UTC, sdementen commented
hello @gregwalters 
thank you for adding tests. however your tests are not testing the functionality you added (the at_date argument and its effect on the results).
can you add tests that specifically test that at_date is taken into account correctly ? on the function itself, can you also add the documentation of the new at_date argument ?

2021-02-22 22:23 UTC, dpslwk commented
use 
`post_date=date(`

not
`post_date=datetime(`

in the tests

2021-02-22 22:25 UTC, gregwalters commented
Yeah, sorry about the noise. I've been a bit lazy about getting the tests running locally :-\

2021-02-24 19:41 UTC, dpslwk requested changes

2021-02-24 19:41 UTC, dpslwk commented on tests/test_account.py
> +        with pytest.raises(GncValidationError):
remove this line and fix indentation of below

2021-02-24 19:41 UTC, dpslwk commented on tests/test_account.py
> +                             post_date=datetime(2014, 1, 1),
`post_date=date(2014, 1, 1),`

2021-02-24 19:41 UTC, dpslwk commented on tests/test_account.py
> +                             splits=splits)
same fix as above

2021-02-24 19:41 UTC, dpslwk commented on tests/test_account.py
> +from piecash import Account, Commodity, Split, Transaction, GncValidationError
remove un-needed `, GncValidationError` once below changes are done

2021-04-02 14:04 UTC, gregwalters commented
Yo @sdementen it looks like the CI stuff is a bit hung up. Otherwise this seems ready to merge. Thoughts?

2021-04-03 09:22 UTC, merged

2021-04-03 09:23 UTC, sdementen commented
tx you all for your contributions!